---
- name: configuring apache2
  hosts: all
  tasks:
   - name: installing apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: editing index.html file
     copy:
      src: /root/example.html
      dest: /var/www/html/index.html
   - name: restarting the service
     service:
      name: apache2
      state: restarted
...
