---
- name: working on node1
  hosts: node1
  tasks:
   - name: install tree
     apt:
      name: tree
      state: present
      update_cache: yes
- name: working on node2
  hosts: node2
  tasks:
   - name: creating user
     user:
      name: ravi
      password: ravi

...
