---
- name: installing packages using global scope
  hosts: all
  tasks:
   - name: install packages
     apt:
      name: "{{package_name}}"
      state: "{{package_state}}"
      update_cache: yes
...
